marketmanager/urls.py
from django.urls import path

from . import views

app_name = "marketmanager"

urlpatterns = [
    path('', views.marketbrowser, name="index"),
    path('marketbrowser', views.marketbrowser, name="marketbrowser"),
    path('marketmanager', views.marketbrowser, name="marketmanager"),
    path('marketwatches', views.marketwatches, name="marketwatches"),
    path(
        'marketbrowser/ajax/search',
        views.marketbrowser_autocomplete,
        name="marketbrowser_autocomplete"
    ),
    path(
        'marketbrowser/ajax/buy_orders',
        views.marketbrowser_buy_orders,
        name="marketbrowser_buy_orders"
    ),
    path(
        'marketbrowser/ajax/sell_orders',
        views.marketbrowser_sell_orders,
        name="marketbrowser_sell_orders"
    ),
    path('char/add', views.add_char, name="add_char"),
    path('corp/add', views.add_corp, name="add_corp")
]

marketmanager/templates/marketmanager/marketbrowser/buy_orders-bs5.html
{% load i18n %}
{% load humanize %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">{% translate "Buy Orders" %}</h4>
    </div>
    <div class="card-body">
        <table class="table table-hover" id="table-buy-orders">
            <thead>
                <tr>
                    <th class="text-left">{% translate "Region" %}</th>
                    <th class="text-left">{% translate "Quantity" %}</th>
                    <th class="text-left">{% translate "Price" %}</th>
                    <th class="text-left">{% translate "Location" %}</th>
                    <th class="text-left">{% translate "Expires" %}</th>
                    <th class="text-left">{% translate "Last Updated" %}</th>
                </tr>
            </thead>
        </table>
        <p class="text-info">{% translate "Owned Character Orders" %}</p>
        <p class="text-success">{% translate "Owned Corporation Orders" %}</p>
    </div>
</div>

marketmanager/templates/marketmanager/marketbrowser/item_details-bs5.html
{% load i18n %}
{% load humanize %}
<div class="row">
    <div class="col-md-7">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    {% if eve_type_icon_url is not None %}
                        <img img-fluid rounded-start src={{ eve_type_icon_url }} alt={{ eve_type.name }} class="img-fluid center-block" />
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">
                            <h6 class="card-subtitle text-body-secondary">
                                {% if eve_type.eve_market_group.parent_market_group.parent_market_group.parent_market_group.parent_market_group is not null %}
                                    {{ eve_type.eve_market_group.parent_market_group.parent_market_group.parent_market_group.parent_market_group }} /
                                {% endif %}
                                {% if eve_type.eve_market_group.parent_market_group.parent_market_group.parent_market_group is not null %}
                                    {{ eve_type.eve_market_group.parent_market_group.parent_market_group.parent_market_group }} /
                                {% endif %}
                                {% if eve_type.eve_market_group.parent_market_group.parent_market_group is not null %}
                                    {{ eve_type.eve_market_group.parent_market_group.parent_market_group }} /
                                {% endif %}
                                {% if eve_type.eve_market_group.parent_market_group is not null %}
                                    {{ eve_type.eve_market_group.parent_market_group }} /
                                {% endif %}
                                {{ eve_type.eve_market_group }}
                            </h6>
                        </p>
                        <h1 class="card-title">{{ eve_type.name }}</h1>
                        <p class="card-text">
                            <small class="text-body-secondary">{{ eve_type.volume }}m3</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="card mb-3">
            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <td>&nbsp;</td>
                            <td>
                                <small>{% translate "5%" %}</small>
                            </td>
                            <td>
                                <small>{% translate "Weighted Average" %}</small>
                            </td>
                            <td>
                                <small>{% translate "Median" %}</small>
                            </td>
                            <td>
                                <small>{% translate "Volume" %}</small>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <small>{% translate "Selling" %}</small>
                            </td>
                            <td>{{ type_statistics.sell_fifth_percentile|intcomma }}</td>
                            <td>{{ type_statistics.sell_weighted_average|intcomma }}</td>
                            <td>{{ type_statistics.sell_median|intcomma }}</td>
                            <td>{{ type_statistics.sell_volume|intcomma }}</td>
                        </tr>
                        <tr>
                            <td>
                                <small>{% translate "Buying" %}</small>
                            </td>
                            <td>{{ type_statistics.buy_fifth_percentile|intcomma }}</td>
                            <td>{{ type_statistics.buy_weighted_average|intcomma }}</td>
                            <td>{{ type_statistics.buy_median|intcomma }}</td>
                            <td>{{ type_statistics.buy_volume|intcomma }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            {% if type_statistics.explain is not null %}<div class="card-footer">{{ type_statistics.explain }}</div>{% endif %}
        </div>
    </div>
</div>

marketmanager/templates/marketmanager/marketbrowser/item_selector-bs5.html
<li class="dropdown">
    <form action="{% url 'marketmanager:marketbrowser' %}"method="get" id="item_selector" class="dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
        {% if eve_region != None %}<input type="hidden" name="region_id" value="{{ eve_region.id }}" />{% endif %}
        <select onchange="this.form.submit()" class="form-control" id="item_selector" name="type_id">
            {% for market_group in parent_market_groups %}
                <option value="{{ market_group.id }}">{{ market_group.name }}</option>
            {% endfor %}
        </select>
    </form>
</li>

marketmanager/templates/marketmanager/marketbrowser/region_selector-bs5.html
<form action="{% url 'marketmanager:marketbrowser' %}" method="get" id="region_selector" class="d-flex dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
    {% if eve_type != None %}<input type="hidden" name="type_id" value={{ eve_type.id }} />{% endif %}
    <select onchange="this.form.submit()" class="form-control" id="region_selector" name="region_id">
        <option value="None" {% if eve_region is None %}selected{% endif %}>New Eden (All)</option>
        {% for each_region in all_regions %}
            <option value={{ each_region.id }} {% if eve_region.id == each_region.id %}selected{% endif %}>
                {{ each_region.name }}
            </option>
        {% endfor %}
    </select>
</form>

marketmanager/templates/marketmanager/marketbrowser/search-bs5.html
<form class="d-flex" role="search" action="{% url 'marketmanager:marketbrowser' %}" method="get">
    <div class="form-group">
        <input type="text" id="search" value class="form-control" placeholder="Search" />
    </div>
</form>

marketmanager/templates/marketmanager/marketbrowser/sell_orders-bs5.html
{% load i18n %}
{% load humanize %}
<div class="card mb-2">
    <div class="card-header">
        <h4 class="card-title">{% translate "Sell Orders" %}</h4>
    </div>
    <div class="card-body">
        <table class="table table-hover" id="table-sell-orders">
            <thead>
                <tr>
                    <th class="text-left">{% translate "Region" %}</th>
                    <th class="text-left">{% translate "Quantity" %}</th>
                    <th class="text-left">{% translate "Price" %}</th>
                    <th class="text-left">{% translate "Location" %}</th>
                    <th class="text-left">{% translate "Expires" %}</th>
                    <th class="text-left">{% translate "Last Updated" %}</th>
                </tr>
            </thead>
        </table>
        <p class="text-info">{% translate "Owned Character Orders" %}</p>
        <p class="text-success">{% translate "Owned Corporation Orders" %}</p>
    </div>
</div>