marketmanager/urls.py
from django.urls import path

from . import views

app_name = "marketmanager"

urlpatterns = [
    path('', views.marketbrowser, name="index"),
    path('marketbrowser', views.marketbrowser, name="marketbrowser"),
    path('marketmanager', views.marketbrowser, name="marketmanager"),
    path('marketwatches', views.marketwatches, name="marketwatches"),
    path(
        'marketbrowser/ajax/search',
        views.marketbrowser_autocomplete,
        name="marketbrowser_autocomplete"
    ),
    path(
        'marketbrowser/ajax/buy_orders',
        views.marketbrowser_buy_orders,
        name="marketbrowser_buy_orders"
    ),
    path(
        'marketbrowser/ajax/sell_orders',
        views.marketbrowser_sell_orders,
        name="marketbrowser_sell_orders"
    ),
    path('char/add', views.add_char, name="add_char"),
    path('corp/add', views.add_corp, name="add_corp")
]

marketmanager/templates/marketmanager/base-bs5.html
{% extends "allianceauth/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block page_title %}
    {% translate "Market Manager" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Market Manager" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    <ul class="nav-item">
        {% include "marketmanager/marketbrowser/search-bs5.html" %}
    </ul>
    <ul class="nav-item dropdown">
        {% include "marketmanager/marketbrowser/region_selector-bs5.html" %}
    </ul>
{% endblock header_nav_collapse_left %}

{% block header_nav_collapse_right %}
    <li class="nav-item">
        <a href="{% url 'marketmanager:add_char' %}" class="nav-link">{% translate "Add Character Token" %}</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'marketmanager:add_corp' %}" class="nav-link">{% translate "Add Corporate Token" %}</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'marketmanager:marketwatches' %}" class="nav-link">{% translate "Market Watch Status" %}</a>
    </li>
{% endblock header_nav_collapse_right %}

{% block content %}
{% endblock content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/jquery-ui-js.html" %}
    {% include "bundles/moment-js.html" %}
{% endblock extra_javascript %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
    {% include "bundles/jquery-ui-css.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'marketmanager/css/marketmanager.css' %}" />
{% endblock extra_css %}

marketmanager/templates/marketmanager/marketbrowser-bs5.html
{% extends "marketmanager/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block page_title %}
    {% translate "Market Browser" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Market Browser" %}
{% endblock header_nav_brand %}

{% block content %}
    {% include "marketmanager/marketbrowser/item_details-bs5.html" %}
    <div class="col-lg-12">
        {% include "marketmanager/marketbrowser/sell_orders-bs5.html" %}
        {% include "marketmanager/marketbrowser/buy_orders-bs5.html" %}
    </div>
{% endblock content %}

{% block extra_script %}
    $(document).ready(function(){
    $('#table-sell-orders').DataTable({
    {% if eve_type.id is not None %}
        "ajax": {
        "url": "{% url 'marketmanager:marketbrowser_sell_orders' %}",
        "dataSrc": "sell_orders",
        "data": {
        {% if eve_region is not None %}"region_id": {{ eve_region.id }},{% endif %}
        "type_id": {{ eve_type.id }}
        }
        },
    {% endif %}
    columns: [
    {
    data: "eve_region__name"
    },
    {
    data: "volume_remain",
    render: $.fn.dataTable.render.number(',', '.', 0, null, "")
    },
    {
    data: 'price',
    render: $.fn.dataTable.render.number(',', '.', 2, null, " ISK")
    },
    {
    data: "location_resolved"
    },
    {
    data: "expiry_calculated"
    },
    {
    data: "updated_at"
    },
    ],
    "fnRowCallback": function(nRow, aData) {
    if (aData["user_is_owner"] == true) {
    $('td', nRow).addClass('bg-info');
    };
    if (aData["corporation_is_owner"] == true) {
    $('td', nRow).addClass('bg-success');
    }
    },
    "order": [[ 2, "asc" ]],
    "processing": true,
    "stateSave": true,
    "stateDuration": 0
    } );

    $('#table-buy-orders').DataTable({
    {% if eve_type.id is not None %}
        "ajax": {
        "url": "{% url 'marketmanager:marketbrowser_buy_orders' %}",
        "dataSrc": "buy_orders",
        "data": {
        {% if eve_region is not None %}"region_id": {{ eve_region.id }},{% endif %}
        "type_id": {{ eve_type.id }}
        }
        },
    {% endif %}
    columns: [
    {
    data: "eve_region__name"
    },
    {
    data: "volume_remain",
    render: $.fn.dataTable.render.number(',', '.', 0, null, "")
    },
    {
    data: 'price',
    render: $.fn.dataTable.render.number(',', '.', 2, null, " ISK")
    },
    {
    data: "location_resolved"
    },
    {
    data: "expiry_calculated"
    },
    {
    data: "updated_at"
    },
    ],
    "fnRowCallback": function(nRow, aData) {
    if (aData["user_is_owner"] == true) {
    $('td', nRow).addClass('bg-info');
    };
    if (aData["corporation_is_owner"] == true) {
    $('td', nRow).addClass('bg-success');
    }
    },
    "order": [[ 2, "desc" ]],
    "processing": true,
    "stateSave": true,
    "stateDuration": 0
    } );
    });

    $(document).ready(function() {
    $("#search").autocomplete({
    source: "{% url 'marketmanager:marketbrowser_autocomplete' %}",
    minLength: 3,
    autoFocus: true,
    select: function(event, ui){
    SearchTypeID(ui.item.label, ui.item.value);
    event.preventDefault();
    },
    focus: function(event, ui){
    event.preventDefault();
    },
    });
    });

    function SearchTypeID(eve_type_name, eve_type_id) {
    window.location.href = "?type_id="+eve_type_id
    {% if eve_region != None %}+"&region_id="+ {{ eve_region.id }}{% endif %}
    ;
    }

{% endblock extra_script %}

marketmanager/templates/marketmanager/marketwatches-bs5.html
{% extends "marketmanager/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block page_title %}
    {% translate "Market Watches" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Market Watches" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    {% comment %} Empty this block out {% endcomment %}
{% endblock header_nav_collapse_left %}

{% block content %}
    {% comment %} for structure in structures, return the watches {% endcomment %}

    <table class="table table-hover" id="table-market-watches">
        <thead>
            <tr>
                <th class="text-left">{% translate "EVE Type" %}</th>
                <th class="text-left">{% translate "Missing Quantity" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for watchconfig in watchconfigs %}
                <tr>
                    <td>{{ watchconfig.eve_type.name }}</td>
                    <td>{{ watchconfig.missing_volume }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

{% block extra_script %}
    $(document).ready( function () {
    $('#table-market-watches').DataTable({
    lengthMenu: [
    [10, 25, 50, 100, -1],
    [10, 25, 50, 100, 'All'],
    ],
    "stateSave": true,
    "stateDuration": 0
    });
    } );
{% endblock extra_script %}